version: '3.4'
name: shop_microservices
services:
  shopmicroservices.productapi.db:
    image: mongo

  shopmicroservices.productapi:
    image: ${DOCKER_REGISTRY-}shopmicroservicesproductapi
    build:
      context: .
      dockerfile: ShopMicroservices.ProductApi/Dockerfile

  shopmicroservices.basketapi.db:
    image: redis:alpine

  shopmicroservices.basketapi:
    image: ${DOCKER_REGISTRY-}shopmicroservicesbasketapi
    build:
      context: .
      dockerfile: ShopMicroservices.BasketApi/Dockerfile

  shopmicroservices.discountapi.db:
    image: postgres

  shopmicroservices.discountapi.pgadmin:
    image: dpage/pgadmin4

  shopmicroservices.discountapi:
    image: ${DOCKER_REGISTRY-}shopmicroservicesdiscountapi
    build:
      context: .
      dockerfile: ShopMicroservices.DiscountApi/Dockerfile

  masstransit.rabbitmq:
    image: masstransit/rabbitmq

  shopmicroservices.consul:
    image: "hashicorp/consul"

  shopmicroservices.gatewayapi:
    image: ${DOCKER_REGISTRY-}shopmicroservicesgatewayapi
    build:
      context: .
      dockerfile: ShopMicroservices.GatewayApi/Dockerfile

