version: '3.4'

services:
  shopmicroservices.productapi.db:
    container_name: productapidb
    restart: always
    ports:
        - "27017:27017" 

  shopmicroservices.productapi:
    container_name: shopmicroservices.productapi
    depends_on:
      - shopmicroservices.productapi.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__ConnectionString=mongodb://productapidb:27017"  
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
  
  shopmicroservices.basketapi.db:
    container_name: basketapidb
    restart: always
    ports:
        - "6379:6379" 

  shopmicroservices.basketapi:
    container_name: shopmicroservices.basketapi
    depends_on:
      - shopmicroservices.basketapi.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CacheSettings__ConnectionString=basketapidb:6379
      - ASPNETCORE_HTTP_PORTS=8082
      - ASPNETCORE_HTTPS_PORTS=8083
    ports:
      - "8082:8082"
      - "8083:8083"

  shopmicroservices.discountapi.db:
    container_name: discountapidb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
      
  shopmicroservices.discountapi.pgadmin:
    container_name: shopmicroservices.discountapi.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80" 

  shopmicroservices.discountapi:
    container_name: shopmicroservices.discountapi
    depends_on:
      - shopmicroservices.discountapi.db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8084
      - ASPNETCORE_HTTPS_PORTS=8085
      - DatabaseSettings__ConnectionString=Server=discountapidb:5432;Database=DiscountDb;User ID=admin;Password=admin
    ports:
      - "8084:8084"
      - "8085:8085"
