version: '3.4'
name: shop_microservices
services:
  shopmicroservices.productapi.db:
    image: mongo
    container_name: shopmicroservices.productapi.db

  shopmicroservices.productapi:
    image: ${DOCKER_REGISTRY-}shopmicroservicesproductapi
    build:
      context: .
      dockerfile: ShopMicroservices.ProductApi/Dockerfile

  shopmicroservices.basketapi.db:
    image: redis:alpine
    container_name: shopmicroservices.basketapi.db

  shopmicroservices.basketapi:
    image: ${DOCKER_REGISTRY-}shopmicroservicesbasketapi
    build:
      context: .
      dockerfile: ShopMicroservices.BasketApi/Dockerfile

